<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpvzmyn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpvzmyn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXpvzmyn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXpvzmyn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXpvzmyn\appProdProjectContainer([
    'container.build_hash' => 'Xpvzmyn',
    'container.build_id' => '217706cb',
    'container.build_time' => 1607622428,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpvzmyn');
